### ISSUE TITLE
DHT11 library

### ISSUE THREAD

**Issue by rebound123** [Robotistan/PicoBricks#1]
picobricks.py doesn't define the DHT11 library. Version of picobricks.py included in the kit includes additional lines from 625 onwards to define DHT11.

[PicoBricks](https://github.com/Robotistan/PicoBricks)/[Examples](https://github.com/Robotistan/PicoBricks/tree/main/Examples)/[Pre-Installed Code](https://github.com/Robotistan/PicoBricks/tree/main/Examples/Pre-Installed%20Code)/picobricks.py

**Comment by MSMorkan-Robo** [comment]
Hi,

We updated the mentioned library and Pre-installed code.
