### ISSUE TITLE
Incorrect code

### ISSUE THREAD

**Issue by Wizzard1313** [Robotistan/PicoBricks#7]
https://github.com/Robotistan/PicoBricks/blob/44a7e9eb7d66a9cdd9d346209b5fea9ddad7791f/Examples/Activities/Graphic%20Monitor/graphic-monitor-arduino/graphic_monitor_arduino.ino#L14
This line should be an analogWrite instead of a digitalWrite.

**Comment by amet7** [comment]
Thanks your feedback. It is solved.
